/**
 * Current FactMem schema as Postgres DDL.
 *
 * SQLite keeps its incremental PRAGMA migrations — that history is SQLite's.
 * A new Postgres store is created at the current version in one shot
 * (migrations table, not user_version). Not a second knowledge store: D, I,
 * and K are tables in one database; tsvector is the word index of K, matching
 * FTS5 on SQLite.
 */

import type { Db } from "./connection.js";
import { SCHEMA_VERSION } from "./schema-version.js";
import { seedExtractWatermarksFromConsolidations } from "./extract-watermarks.js";

export async function postgresSchemaVersion(db: Db): Promise<number> {
  const row = (await db
    .prepare(
      `SELECT COALESCE(MAX(version), 0) AS user_version FROM schema_migrations`,
    )
    .get()) as { user_version: number } | undefined;
  return Number(row?.user_version ?? 0);
}

export async function applyPostgresSchema(db: Db): Promise<void> {
  const version = await postgresSchemaVersionSafe(db);
  if (version >= SCHEMA_VERSION) return;
  await db.exec(POSTGRES_DDL);
  // CREATE IF NOT EXISTS does not replace a CHECK. Existing stores that
  // opened at v17 still have the three-value constraint.
  if (version > 0 && version < 18) {
    await applyPostgresV18(db);
  }
  if (version > 0 && version < 19) {
    await seedExtractWatermarksFromConsolidations(db);
  }
  if (version > 0 && version < 21) {
    await db.exec(`ALTER TABLE inferences ADD COLUMN IF NOT EXISTS metadata TEXT;`);
  }
  if (version > 0 && version < 22) {
    await db.exec(`
      ALTER TABLE intelligence_runs ADD COLUMN IF NOT EXISTS trigger TEXT;
      ALTER TABLE intelligence_runs ADD COLUMN IF NOT EXISTS source_tool TEXT;
      ALTER TABLE intelligence_runs ADD COLUMN IF NOT EXISTS project TEXT;
    `);
  }
  if (version > 0 && version < 23) {
    await applyPostgresV23(db);
  }
  await db
    .prepare(`INSERT OR IGNORE INTO schema_migrations (version) VALUES (?)`)
    .run(SCHEMA_VERSION);
}

async function applyPostgresV18(db: Db): Promise<void> {
  await db.exec(`
    DO $v18$
    DECLARE
      r RECORD;
    BEGIN
      FOR r IN
        SELECT c.conname
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE t.relname = 'session_fact_sources'
          AND n.nspname = current_schema()
          AND c.contype = 'c'
          AND pg_get_constraintdef(c.oid) LIKE '%extraction_type%'
      LOOP
        EXECUTE format('ALTER TABLE session_fact_sources DROP CONSTRAINT %I', r.conname);
      END LOOP;
    END
    $v18$;
    ALTER TABLE session_fact_sources
      ADD CONSTRAINT session_fact_sources_extraction_type_check
      CHECK (extraction_type IN (
        'primary', 'corroborating', 'contextual',
        'assent', 'observation', 'restatement'
      ));
  `);
}

async function applyPostgresV23(db: Db): Promise<void> {
  await db.exec(`
    DO $v23$
    DECLARE
      r RECORD;
    BEGIN
      FOR r IN
        SELECT t.relname AS tbl, c.conname
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE t.relname IN ('facts', 'session_facts')
          AND n.nspname = current_schema()
          AND c.contype = 'c'
          AND pg_get_constraintdef(c.oid) LIKE '%source_quality%'
      LOOP
        EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', r.tbl, r.conname);
      END LOOP;
      IF to_regclass('facts') IS NOT NULL THEN
        EXECUTE $c$
          ALTER TABLE facts
            ADD CONSTRAINT facts_source_quality_check
            CHECK (source_quality IN ('heuristic', 'cli', 'sampling', 'explicit', 'http'))
        $c$;
      END IF;
      IF to_regclass('session_facts') IS NOT NULL THEN
        EXECUTE $c$
          ALTER TABLE session_facts
            ADD CONSTRAINT session_facts_source_quality_check
            CHECK (source_quality IN ('heuristic', 'cli', 'sampling', 'explicit', 'http'))
        $c$;
      END IF;
    END
    $v23$;
  `);
}

async function postgresSchemaVersionSafe(db: Db): Promise<number> {
  try {
    return await postgresSchemaVersion(db);
  } catch {
    return 0;
  }
}

/**
 * Current shape (schema v20). `rowid` is an identity column so SQLite queries
 * that join FTS on rowid or order by insert order still have a column to use.
 * Word search is `tsvector` + GIN, not FTS5.
 */
const POSTGRES_DDL = `
CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  source_tool TEXT,
  project TEXT,
  started_at TIMESTAMPTZ NOT NULL,
  last_activity_at TIMESTAMPTZ NOT NULL,
  rowid BIGINT GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE IF NOT EXISTS session_events (
  id TEXT PRIMARY KEY,
  mcp_session_id TEXT,
  client_session_id TEXT,
  sequence INTEGER NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('message', 'tool_call', 'tool_result', 'artifact')),
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'tool')),
  content_type TEXT NOT NULL DEFAULT 'text' CHECK (content_type IN ('text', 'json', 'image', 'audio', 'binary')),
  content TEXT,
  content_ref TEXT,
  metadata TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  occurred_at TIMESTAMPTZ,
  speaker TEXT,
  rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  content_tsv tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(content, ''))) STORED
);
CREATE INDEX IF NOT EXISTS idx_session_events_session_mcp ON session_events(mcp_session_id, sequence);
CREATE INDEX IF NOT EXISTS idx_session_events_session_client ON session_events(client_session_id, sequence);
CREATE INDEX IF NOT EXISTS idx_session_events_tsv ON session_events USING GIN (content_tsv);

CREATE TABLE IF NOT EXISTS session_facts (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  content TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  source_origin TEXT NOT NULL DEFAULT 'explicit'
    CHECK (source_origin IN ('explicit', 'inferred')),
  source_event_id TEXT,
  domain_hint TEXT,
  subdomain_hint TEXT,
  confidence DOUBLE PRECISION,
  importance DOUBLE PRECISION,
  confidence_signal DOUBLE PRECISION,
  importance_signal DOUBLE PRECISION,
  valid_from_hint TIMESTAMPTZ,
  valid_until_hint TIMESTAMPTZ,
  entities_json TEXT,
  source_quality TEXT NOT NULL DEFAULT 'heuristic'
    CHECK (source_quality IN ('heuristic', 'cli', 'sampling', 'explicit', 'http')),
  source_tool TEXT,
  capture_context TEXT,
  consolidation_id TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  speaker_role TEXT CHECK (speaker_role IS NULL OR speaker_role IN ('user', 'assistant', 'system', 'tool')),
  speaker TEXT,
  rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  content_tsv tsvector GENERATED ALWAYS AS (to_tsvector('simple', content)) STORED
);
CREATE INDEX IF NOT EXISTS idx_session_facts_session ON session_facts(session_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_session_facts_hash ON session_facts(session_id, content_hash);
CREATE INDEX IF NOT EXISTS idx_session_facts_unclaimed ON session_facts(created_at) WHERE consolidation_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_session_facts_tsv ON session_facts USING GIN (content_tsv);

CREATE TABLE IF NOT EXISTS session_fact_sources (
  session_fact_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  relevance DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  extraction_type TEXT NOT NULL DEFAULT 'contextual',
  PRIMARY KEY (session_fact_id, event_id),
  CONSTRAINT session_fact_sources_extraction_type_check
    CHECK (extraction_type IN (
      'primary', 'corroborating', 'contextual',
      'assent', 'observation', 'restatement'
    ))
);

CREATE TABLE IF NOT EXISTS domains (
  name TEXT PRIMARY KEY,
  subdomains TEXT NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS consolidation_lock (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  holder TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS facts (
  id TEXT PRIMARY KEY,
  content TEXT NOT NULL,
  domain TEXT NOT NULL,
  subdomain TEXT,
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.7,
  importance DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  source_type TEXT NOT NULL,
  source_tool TEXT,
  source_id TEXT,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'superseded', 'rejected')),
  superseded_by TEXT,
  is_latest INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL,
  valid_from TIMESTAMPTZ,
  valid_until TIMESTAMPTZ,
  system_retired_at TIMESTAMPTZ,
  session_id TEXT,
  capture_context TEXT,
  access_count INTEGER NOT NULL DEFAULT 0,
  source_quality TEXT NOT NULL DEFAULT 'heuristic'
    CHECK (source_quality IN ('heuristic', 'cli', 'sampling', 'explicit', 'http')),
  speaker_role TEXT CHECK (speaker_role IS NULL OR speaker_role IN ('user', 'assistant', 'system', 'tool')),
  speaker TEXT,
  rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  content_tsv tsvector GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(content, '') || ' ' || coalesce(domain, '') || ' ' || coalesce(subdomain, ''))
  ) STORED
);
CREATE INDEX IF NOT EXISTS idx_facts_domain ON facts(domain, subdomain);
CREATE INDEX IF NOT EXISTS idx_facts_status ON facts(status, is_latest);
CREATE INDEX IF NOT EXISTS idx_facts_session ON facts(session_id);
CREATE INDEX IF NOT EXISTS idx_facts_tsv ON facts USING GIN (content_tsv);

CREATE TABLE IF NOT EXISTS entities (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  canonical_name TEXT NOT NULL,
  metadata TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  access_count INTEGER NOT NULL DEFAULT 0,
  last_accessed_at TIMESTAMPTZ,
  is_self INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_entities_type ON entities(type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_entities_canonical_type ON entities(canonical_name, type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_entities_self ON entities(is_self) WHERE is_self = 1;

CREATE TABLE IF NOT EXISTS fact_entities (
  fact_id TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  relationship TEXT NOT NULL,
  PRIMARY KEY (fact_id, entity_id, relationship)
);
CREATE INDEX IF NOT EXISTS idx_fact_entities_entity ON fact_entities(entity_id);

CREATE TABLE IF NOT EXISTS entity_edges (
  from_entity TEXT NOT NULL,
  to_entity TEXT NOT NULL,
  relationship TEXT NOT NULL,
  strength DOUBLE PRECISION NOT NULL,
  metadata TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  last_accessed_at TIMESTAMPTZ,
  PRIMARY KEY (from_entity, to_entity, relationship)
);
CREATE INDEX IF NOT EXISTS idx_entity_edges_from ON entity_edges(from_entity);
CREATE INDEX IF NOT EXISTS idx_entity_edges_to ON entity_edges(to_entity);

CREATE TABLE IF NOT EXISTS sources (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  tool_id TEXT,
  timestamp TIMESTAMPTZ NOT NULL,
  raw_content TEXT,
  metadata TEXT
);

CREATE TABLE IF NOT EXISTS consolidations (
  id TEXT PRIMARY KEY,
  session_id TEXT,
  facts_in INTEGER NOT NULL,
  facts_graduated INTEGER NOT NULL,
  facts_rejected INTEGER NOT NULL,
  entities_created INTEGER NOT NULL DEFAULT 0,
  entities_linked INTEGER NOT NULL DEFAULT 0,
  supersessions INTEGER NOT NULL DEFAULT 0,
  summary TEXT,
  open_threads TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  last_event_sequence INTEGER NOT NULL DEFAULT 0,
  now TEXT,
  now_start_sequence INTEGER,
  now_referents TEXT,
  segments TEXT,
  rowid BIGINT GENERATED BY DEFAULT AS IDENTITY
);
CREATE INDEX IF NOT EXISTS idx_consolidations_created ON consolidations(created_at);
CREATE INDEX IF NOT EXISTS idx_consolidations_session ON consolidations(session_id);

CREATE TABLE IF NOT EXISTS fact_embeddings (
  fact_id TEXT PRIMARY KEY,
  model TEXT NOT NULL,
  dimensions INTEGER NOT NULL,
  vector BYTEA NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fact_embeddings_model ON fact_embeddings(model, dimensions);

CREATE TABLE IF NOT EXISTS source_watermarks (
  path TEXT PRIMARY KEY,
  byte_offset INTEGER NOT NULL,
  line_number INTEGER NOT NULL,
  fingerprint TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS extract_watermarks (
  kind TEXT NOT NULL CHECK (kind IN ('client', 'mcp', 'unkeyed')),
  conversation_id TEXT NOT NULL,
  last_event_sequence INTEGER NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (kind, conversation_id)
);

CREATE TABLE IF NOT EXISTS inferences (
  id TEXT PRIMARY KEY,
  hypothesis TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'confirmed', 'rejected')),
  reason TEXT,
  fact_id TEXT,
  metadata TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  validated_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_inferences_status ON inferences(status, created_at);

CREATE TABLE IF NOT EXISTS inference_evidence (
  inference_id TEXT NOT NULL,
  fact_id TEXT NOT NULL,
  PRIMARY KEY (inference_id, fact_id)
);

CREATE TABLE IF NOT EXISTS intelligence_runs (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('consolidate', 'capture')),
  consolidation_id TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  usage TEXT NOT NULL,
  trigger TEXT,
  source_tool TEXT,
  project TEXT
);
CREATE INDEX IF NOT EXISTS idx_intelligence_runs_created ON intelligence_runs(created_at);
`;
